add verification views
Laravel-Backpack/theme-coreuiv4 pull request #48
Opened 2023-08-29 14:28 UTC by pxpm

This PR should be merged when https://github.com/Laravel-Backpack/CRUD/pull/5301 gets merged.

![image](https://github.com/Laravel-Backpack/theme-coreuiv4/assets/7188159/99d83387-0975-4d6f-bbcd-3d6104ad2443)

2023-08-29 17:41 UTC, tabacitu commented
This probably needs a little love too. Card to be narrower. Spacing before&after the card itself.

What I would do is copy-paste the EXACT view from registration. And just change the card content. That way, when people move from the Register screen to the Verify screen, it's seamless. Only the card content seems to change.

2023-08-29 21:36 UTC, pxpm commented
![image](https://github.com/Laravel-Backpack/theme-coreuiv4/assets/7188159/a75e8ee4-6306-4dbe-ad3b-58bd75382ba4)

2023-08-30 10:11 UTC, tabacitu requested changes

2023-08-30 10:11 UTC, tabacitu commented on resources/views/auth/verify-email.blade.php
> +        <div class="card p-4 mb-0">
```suggestion
        <div class="card mb-0">
```

2023-08-30 10:11 UTC, tabacitu commented on resources/views/auth/verify-email.blade.php
> +                <div class="mb-4 mt-2">
```suggestion
                <div class="mt-3">
```

2023-08-30 10:11 UTC, tabacitu commented on resources/views/auth/verify-email.blade.php
> +                    <div class="alert alert-success" role="alert">
```suggestion
                    <div class="alert alert-success my-0" role="alert">
```

2023-08-31 10:03 UTC, merged